### ISSUE TITLE
cvdupdate support on pypi

### ISSUE THREAD

**Issue by colton-freeman** [Cisco-Talos/cvdupdate#60]
good day all,
is the cvdupdate still supported on pypi? last push was back in 2022. https://pypi.org/project/cvdupdate/1.1.1/
from my understanding the freshclam command does the same thing but just curious.

**Comment by micahsnyder** [comment]
We haven't had a release since 2022.  We've made a couple minor improvements since then. It couldn't hurt to publish a 1.1.2 patch version.

**Comment by micahsnyder** [comment]
Regarding freshclam vs cvdupdate -- freshclam is intended to keep a specific clamav installation up to date.  cvdupdate is intended to keep a database mirror  up to date - which requires more files. 

If you already have a recent database (newer than 90 days), freshclam will update from that using one or more `.cdiff` patch files.  This downloads the minimum data required for the update.  

cvdupdate, on the other hand, will download each `.cdiff` file since your current `.cvd` up to the latest `.cvd` plus the latest whole `.cvd` file.  So that's at least 2 file downloads and the `.cvd` file download which for `daily.cvd` is about 62MB right now.

**Comment by colton-freeman** [comment]
ahh, so cvdupdate is probably the way to go but i can see the downsides. i wouldnt say no to a 1.1.2 but if 1.1.1 works as expected then thats good with us. thank you for the info and the quick response.
